/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.feebe.RingTone;

public final class R {
    public static final class array {
        /**  Ringtypes 
         */
        public static final int ring_types=0x7f060002;
        /**  Used in RingActivity/share 
         */
        public static final int select_share_methods=0x7f060000;
        /**  Used in Ring/menu_unsetRingtone 
         */
        public static final int select_unset_ringtone=0x7f060001;
    }
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundColor=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int isGoneWithoutAd=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int keywords=0x7f010003;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int refreshInterval=0x7f010004;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int testing=0x7f010000;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textColor=0x7f010002;
    }
    public static final class drawable {
        public static final int button_zoom_in=0x7f020000;
        public static final int button_zoom_out=0x7f020001;
        public static final int grid_line=0x7f02001d;
        public static final int ic_media_next=0x7f020002;
        public static final int ic_media_previous=0x7f020003;
        public static final int marker_left=0x7f020004;
        public static final int marker_left_focused=0x7f020005;
        public static final int marker_left_normal=0x7f020006;
        public static final int marker_left_pressed=0x7f020007;
        public static final int marker_right=0x7f020008;
        public static final int marker_right_focused=0x7f020009;
        public static final int marker_right_normal=0x7f02000a;
        public static final int marker_right_pressed=0x7f02000b;
        public static final int minitab_focus=0x7f02000c;
        public static final int minitab_press=0x7f02000d;
        public static final int minitab_selected=0x7f02000e;
        public static final int minitab_unselected=0x7f02000f;
        public static final int playback_indicator=0x7f02001c;
        public static final int ring=0x7f020010;
        public static final int selection_border=0x7f02001b;
        public static final int tab_browse=0x7f020011;
        public static final int tab_download=0x7f020012;
        public static final int tab_hot=0x7f020013;
        public static final int tab_search=0x7f020014;
        public static final int tab_small_indicator=0x7f020015;
        public static final int timecode=0x7f02001e;
        public static final int timecode_shadow=0x7f02001f;
        public static final int type_bkgnd_alarm=0x7f020020;
        public static final int type_bkgnd_music=0x7f020023;
        public static final int type_bkgnd_notification=0x7f020022;
        public static final int type_bkgnd_ringtone=0x7f020021;
        public static final int type_bkgnd_unsupported=0x7f020024;
        public static final int type_music=0x7f020016;
        public static final int type_ringtone=0x7f020017;
        public static final int waveform_selected=0x7f020018;
        public static final int waveform_unselected=0x7f020019;
        public static final int waveform_unselected_bkgnd_overlay=0x7f02001a;
    }
    public static final class id {
        public static final int AdsView=0x7f090019;
        public static final int Info=0x7f09002d;
        public static final int about_ringtone=0x7f09002f;
        public static final int ad=0x7f09001a;
        public static final int ad_in_editor=0x7f090015;
        public static final int ad_in_searchtab=0x7f090037;
        public static final int assign=0x7f090028;
        public static final int button_choose_contact=0x7f090001;
        public static final int button_do_nothing=0x7f090002;
        public static final int button_make_default=0x7f090000;
        public static final int cancel=0x7f090018;
        public static final int detailLayout2=0x7f090023;
        public static final int download=0x7f090025;
        public static final int edit=0x7f09002a;
        public static final int endmarker=0x7f090009;
        public static final int endtext=0x7f090013;
        public static final int ffwd=0x7f09000d;
        public static final int filename=0x7f090017;
        public static final int info=0x7f09000a;
        public static final int info_text=0x7f09002e;
        public static final int input_artist=0x7f090034;
        public static final int input_title=0x7f090036;
        public static final int layoutMyReview=0x7f09002b;
        public static final int linearLayout1=0x7f090021;
        public static final int list_searchOthers=0x7f090030;
        public static final int mark_end=0x7f090011;
        public static final int mark_start=0x7f090010;
        public static final int play=0x7f09000c;
        public static final int preview=0x7f090024;
        public static final int queue=0x7f090026;
        public static final int ratingBar=0x7f09002c;
        public static final int record=0x7f09001b;
        public static final int rew=0x7f09000b;
        public static final int ringListItem1=0x7f090032;
        public static final int ringlist=0x7f090031;
        public static final int ringtone_type=0x7f090016;
        public static final int row_album=0x7f09001e;
        public static final int row_artist=0x7f09001d;
        public static final int row_display_name=0x7f090006;
        public static final int row_icon=0x7f09001c;
        public static final int row_ringtone=0x7f090004;
        public static final int row_small_ratingbar=0x7f090022;
        public static final int row_starred=0x7f090005;
        public static final int row_title=0x7f09001f;
        public static final int save=0x7f090014;
        public static final int search_artist=0x7f090033;
        public static final int search_button=0x7f090038;
        public static final int search_filter=0x7f090003;
        public static final int serach_title=0x7f090035;
        public static final int set=0x7f090027;
        public static final int share=0x7f090029;
        public static final int startmarker=0x7f090008;
        public static final int starttext=0x7f090012;
        public static final int tab_image=0x7f090039;
        public static final int tab_label=0x7f09003a;
        public static final int throbber=0x7f090020;
        public static final int waveform=0x7f090007;
        public static final int zoom_in=0x7f09000e;
        public static final int zoom_out=0x7f09000f;
    }
    public static final class layout {
        public static final int after_save_action=0x7f030000;
        public static final int choose_contact=0x7f030001;
        public static final int contact_row=0x7f030002;
        public static final int editor=0x7f030003;
        public static final int file_save=0x7f030004;
        public static final int list=0x7f030005;
        public static final int main=0x7f030006;
        public static final int media_select=0x7f030007;
        public static final int media_select_row=0x7f030008;
        public static final int pending_view=0x7f030009;
        public static final int ring=0x7f03000a;
        public static final int ring_list_item=0x7f03000b;
        public static final int search_tab=0x7f03000c;
        public static final int searchlist_row=0x7f03000d;
        public static final int tabheader=0x7f03000e;
    }
    public static final class raw {
        public static final int feed=0x7f050000;
    }
    public static final class string {
        public static final int about=0x7f070014;
        public static final int alert_no_button=0x7f070056;
        public static final int alert_ok_button=0x7f070054;
        public static final int alert_title_failure=0x7f070053;
        /** 
     Success and error messages
     
         */
        public static final int alert_title_success=0x7f070052;
        public static final int alert_yes_button=0x7f070055;
        public static final int alertdialog_cancel=0x7f07003c;
        public static final int alertdialog_ok=0x7f07003b;
        /** 
     AlertDialogs
     
         */
        public static final int alertdialog_select=0x7f07003a;
        public static final int alertdialog_share=0x7f07003d;
        public static final int app_name=0x7f070004;
        public static final int artist_name=0x7f07000f;
        public static final int bad_extension_error=0x7f070062;
        /** 
     imported
     
         */
        public static final int button_start_record_activity=0x7f070026;
        public static final int choose_contact_ringtone_button=0x7f070031;
        /** 
     Choose Contact Activity
     
         */
        public static final int choose_contact_title=0x7f070064;
        public static final int clear_cache=0x7f07000a;
        public static final int confirm_delete_ringdroid=0x7f07004e;
        public static final int context_menu_delete=0x7f07003f;
        /** 
     Context menu items
     
         */
        public static final int context_menu_edit=0x7f07003e;
        public static final int default_ringtone_success_message=0x7f070058;
        public static final int delete_alarm=0x7f07004a;
        public static final int delete_audio=0x7f07004d;
        public static final int delete_cancel_button=0x7f070050;
        public static final int delete_failed=0x7f070051;
        public static final int delete_music=0x7f07004c;
        public static final int delete_notification=0x7f07004b;
        public static final int delete_ok_button=0x7f07004f;
        /** 
     Delete confirmation dialog
     
         */
        public static final int delete_ringtone=0x7f070049;
        public static final int delete_tmp_error=0x7f07005b;
        public static final int dlprogress_message=0x7f07001f;
        /** 
     used in RingActivity dlProgress dialog
     
         */
        public static final int dlprogress_title=0x7f07001e;
        public static final int do_nothing_with_ringtone_button=0x7f070032;
        public static final int download_failed=0x7f070060;
        public static final int edit_intent=0x7f07002c;
        public static final int end_label=0x7f07002b;
        public static final int error=0x7f07000e;
        public static final int file_save_button_cancel=0x7f070042;
        public static final int file_save_button_save=0x7f070041;
        /** 
     File Save dialog
     
         */
        public static final int file_save_title=0x7f070040;
        public static final int footer=0x7f070012;
        public static final int info=0x7f070013;
        public static final int info_download_count=0x7f070016;
        public static final int mStreaming_message=0x7f070021;
        /** 
     used in RingActivity mStreaming dialog
     
         */
        public static final int mStreaming_title=0x7f070020;
        public static final int make_default_ringtone_button=0x7f070030;
        public static final int menu_reset=0x7f070036;
        /** 
     Menu items
     
         */
        public static final int menu_save=0x7f070035;
        public static final int menu_search=0x7f070038;
        public static final int menu_show_all_audio=0x7f070037;
        public static final int menu_unset_ringtone=0x7f070039;
        public static final int myreview=0x7f070015;
        public static final int network_error=0x7f070010;
        public static final int no_extension_error=0x7f070063;
        public static final int no_result=0x7f070006;
        public static final int no_sd=0x7f070005;
        public static final int no_sd_space=0x7f070007;
        public static final int no_sdcard=0x7f070028;
        public static final int no_space_error=0x7f070061;
        public static final int no_unique_filename=0x7f07005a;
        public static final int notification_text_failed=0x7f070025;
        /**  
	 used in RingActivity notification when finish or failed download.
	 
         */
        public static final int notification_text_finish=0x7f070024;
        public static final int pause=0x7f07000c;
        public static final int play=0x7f07000b;
        public static final int play_error=0x7f070059;
        /**  Progress dialog text for loading or saving... 
         */
        public static final int progress_dialog_loading=0x7f070033;
        public static final int progress_dialog_saving=0x7f070034;
        public static final int queue=0x7f070017;
        public static final int read_error=0x7f07005f;
        public static final int record_error=0x7f07005c;
        public static final int retry=0x7f070011;
        public static final int ring_picker_message=0x7f070023;
        /** 
     used in RingActivity ring_picker dialog
     
         */
        public static final int ring_picker_title=0x7f070022;
        public static final int ringtone_name_label=0x7f070048;
        public static final int ringtone_type_label=0x7f070043;
        public static final int save_success_message=0x7f070057;
        public static final int sdcard_readonly=0x7f070027;
        public static final int sdcard_shared=0x7f070029;
        public static final int search_hint=0x7f070008;
        /** 
     used in RingActivity search more listview
     
         */
        public static final int search_more=0x7f070018;
        public static final int search_more_by=0x7f070019;
        public static final int search_more_in=0x7f07001a;
        public static final int set_default_notification=0x7f07002f;
        /** 
     used in share alert_dialog
     
         */
        public static final int share_sms1=0x7f07001b;
        public static final int share_sms2=0x7f07001c;
        public static final int share_sms3=0x7f07001d;
        /** 
     Edit activity
     
 Labels next to the start and end time edit boxes 
         */
        public static final int start_label=0x7f07002a;
        public static final int stop=0x7f07000d;
        public static final int success_contact_ringtone=0x7f070065;
        public static final int tab_browse=0x7f070002;
        public static final int tab_download=0x7f070003;
        public static final int tab_hot=0x7f070000;
        public static final int tab_search=0x7f070001;
        public static final int time_seconds=0x7f07002d;
        public static final int too_small_error=0x7f07005d;
        public static final int type_alarm=0x7f070045;
        public static final int type_music=0x7f070044;
        public static final int type_notification=0x7f070046;
        public static final int type_ringtone=0x7f070047;
        public static final int upload=0x7f070009;
        /**  After you save a notification or ringtone and have more options
	 for what to do with them 
         */
        public static final int what_to_do_with_ringtone=0x7f07002e;
        public static final int write_error=0x7f07005e;
    }
    public static final class style {
        public static final int AudioFileInfoOverlayText=0x7f080000;
        public static final int ChooseContactBackground=0x7f080002;
        public static final int HorizontalDividerBottom=0x7f080006;
        public static final int HorizontalDividerTop=0x7f080005;
        public static final int ToolbarBackground=0x7f080001;
        public static final int VerticalDividerLeft=0x7f080003;
        public static final int VerticalDividerRight=0x7f080004;
    }
    public static final class xml {
        public static final int searchable=0x7f040000;
    }
    public static final class styleable {
        /** Attributes that can be used with a com_admob_android_ads_AdView.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_backgroundColor com.feebe.RingTone:backgroundColor}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_isGoneWithoutAd com.feebe.RingTone:isGoneWithoutAd}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_keywords com.feebe.RingTone:keywords}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_refreshInterval com.feebe.RingTone:refreshInterval}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_testing com.feebe.RingTone:testing}</code><td></tr>
           <tr><th><code>{@link #com_admob_android_ads_AdView_textColor com.feebe.RingTone:textColor}</code><td></tr>
           </table>
           @see #com_admob_android_ads_AdView_backgroundColor
           @see #com_admob_android_ads_AdView_isGoneWithoutAd
           @see #com_admob_android_ads_AdView_keywords
           @see #com_admob_android_ads_AdView_refreshInterval
           @see #com_admob_android_ads_AdView_testing
           @see #com_admob_android_ads_AdView_textColor
         */
        public static final int[] com_admob_android_ads_AdView = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005
        };
        /**
          <p>This symbol is the offset where the {@link com.feebe.RingTone.R.attr#backgroundColor}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:backgroundColor
        */
        public static final int com_admob_android_ads_AdView_backgroundColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.feebe.RingTone.R.attr#isGoneWithoutAd}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:isGoneWithoutAd
        */
        public static final int com_admob_android_ads_AdView_isGoneWithoutAd = 5;
        /**
          <p>This symbol is the offset where the {@link com.feebe.RingTone.R.attr#keywords}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:keywords
        */
        public static final int com_admob_android_ads_AdView_keywords = 3;
        /**
          <p>This symbol is the offset where the {@link com.feebe.RingTone.R.attr#refreshInterval}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:refreshInterval
        */
        public static final int com_admob_android_ads_AdView_refreshInterval = 4;
        /**
          <p>This symbol is the offset where the {@link com.feebe.RingTone.R.attr#testing}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:testing
        */
        public static final int com_admob_android_ads_AdView_testing = 0;
        /**
          <p>This symbol is the offset where the {@link com.feebe.RingTone.R.attr#textColor}
          attribute's value can be found in the {@link #com_admob_android_ads_AdView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:textColor
        */
        public static final int com_admob_android_ads_AdView_textColor = 2;
    };
}
