application: chaowebs
version: 1
runtime: python
api_version: 1

default_expiration: 7d # This is good for images, which never change

handlers:
- url: /static
  static_dir: static

- url: /feeds
  static_dir: feeds
  expiration: 10m

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: .*
  script: main.py

